version: '3.2'
services:
  galaxy-postgres:
    image: ${IMAGE_GALAXY_POSTGRES}
    container_name: galaxy-postgres
    hostname: galaxy-postgres
    volumes:
      - type: bind
        source: ${DIR_GALAXY_POSTGRES}
        target: /etc/supervisor
      - type: volume
        source: galaxy-store-vol
        target: /export
    expose:
      - "5432"
    entrypoint: /etc/supervisor/config/startup.sh

  # This container provides the galaxy uwsgi webhandlers, job handlers, nginx
  galaxy-stable:
    image: ${IMAGE_GALAXY_STABLE}
    container_name: galaxy-stable
    depends_on:
      - galaxy-postgres
    env_file: ./env/galaxy-stable
    hostname: galaxy-stable
    privileged: True
    ports:
      - "${GALAXY_PORT}:80" # nginx
    volumes:
        # This is the directory where all your files from Galaxy will be stored on your host system
      - type: volume
        source: galaxy-store-vol
        target: /export

  # PostgreSQL admin suite
  pgadmin4:
    image: ${IMAGE_PGADMIN4}
    container_name: pgadmin4
    ports:
        - "5050:5050"
    volumes:
        # This is the volume to persist pgadmin4 data
      - type: volume
        source: pgadmin4-vol
        target: /pgadmin
    restart: unless-stopped
    depends_on:
      - galaxy-postgres
    labels:
        kompose.service.type: nodeport

volumes:
  # init galaxy-store-data container using the following commands
  #   # create the volume
  #   docker volume create galaxy-store-vol
  #   # optional, inspect resulting volume
  #   docker volume inspect galaxy-store-vol
  #   # create the data-storage container
  #   docker create --mount source=galaxy-store-vol,target=/export --name galaxy-store-data bgruening/galaxy-stable /bin/true
  #   # initialize the data-storage container
  #   docker run --rm -ti -p 8080:80 --volumes-from galaxy-store-data --name galaxy_bootstrap bgruening/galaxy-stable
  #   # Then use ^C to quit after export volume is initialized
  galaxy-store-vol:
    external: true
  # init pgadmin4-data container using the following commands
  #   # create the volume
  #   docker volume create pgadmin4-vol
  pgadmin4-vol:
    external: true
