version: '3.2'
services:

  # Container for Galaxy web (uwsgi webhandlers, job handlers, nginx, etc.)
  galaxy-stable:
    image: ${IMAGE_GALAXY_STABLE}
    container_name: galaxy-stable
    depends_on:
      - galaxy-postgres
    env_file: ./env/galaxy-stable
    hostname: galaxy-stable
    privileged: True
    ports:
      - target: 80
        published: ${GALAXY_PORT}
        protocol: tcp
        mode: host
    volumes:
        # This is the directory where all your files from Galaxy will be stored on your host system
      - type: volume
        source: galaxy-store-vol
        target: /export
      - type: volume
        source: docker-data-vol
        target: /data
      - type: volume
        source: docker-docker-vol
        target: /var/lib/docker
        read_only: true

  # PostgreSQL container
  galaxy-postgres:
    image: ${IMAGE_GALAXY_POSTGRES}
    container_name: galaxy-postgres
    hostname: galaxy-postgres
    volumes:
      - type: bind
        source: ${DIR_GALAXY_POSTGRES}
        target: /etc/supervisor
        read_only: true
      - type: volume
        source: galaxy-store-vol
        target: /export
      - type: volume
        source: docker-data-vol
        target: /data
      - type: volume
        source: docker-docker-vol
        target: /var/lib/docker
        read_only: true
    expose:
      - "5432"
    entrypoint: /etc/supervisor/config/startup.sh

  # PostgreSQL admin suite
  pgadmin4:
    image: ${IMAGE_PGADMIN4}
    container_name: pgadmin4
    ports:
        - "5050:5050"
    volumes:
        # This is the volume to persist pgadmin4 data
      - type: volume
        source: pgadmin4-vol
        target: /pgadmin
      - type: volume
        source: docker-data-vol
        target: /data
      - type: volume
        source: docker-docker-vol
        target: /var/lib/docker
        read_only: true
    restart: unless-stopped
    depends_on:
      - galaxy-postgres

  # proftpd container
  galaxy-proftpd:
    image: ${IMAGE_GALAXY_PROFTPD}
    container_name: galaxy-proftpd
    hostname: galaxy-proftpd
    volumes:
      - type: bind
        source: ${DIR_GALAXY_PROFTPD}
        target: /etc/supervisor
        read_only: true
      - type: volume
        source: galaxy-store-vol
        target: /export
      - type: volume
        source: docker-data-vol
        target: /data
      - type: volume
        source: docker-docker-vol
        target: /var/lib/docker
        read_only: true
    ports:
      - "${GALAXY_FTP_PORT}:21" # ftp - only works in PASV mode at the moment, e.g., 'ftp -p localhost 8021'
      - "${GALAXY_SSH_PORT}:22" # sftp
    restart: always
    depends_on:
      - galaxy-postgres
    entrypoint: /etc/supervisor/config/startup.sh

volumes:
  # init galaxy-store-data container using prep.sh
  galaxy-store-vol:
    external: true
  # init pgadmin4-data container using the following commands
  #   # create the volume
  #   docker volume create pgadmin4-vol
  pgadmin4-vol:
    external: true
  # init volume to be mounted at /var/lib/docker
  docker-docker-vol:
    external: true
  # init volume to be mounted at /data
  docker-data-vol:
    external: true
